name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Test
      run: |
        echo "::set-output name=testoutput::thisisatest.ToUpper()"
      shell: powershell
      id: test 
      
    - name: Test 2
      run: Write-Host steps.test.output.testoutput
